---
- name: Build project
  hosts: build
  vars:
    repo_url: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    repo_dest: /opt/hello-war
  tasks:
    - name: Ensure git and maven are installed
      apt:
        name:
          - git
          - maven
        state: present

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: master
        force: yes

    - name: Build the WAR with Maven
      command: mvn package -X
      args:
        chdir: "{{ repo_dest }}"

    - name: Fetch built WAR to controller
      fetch:
        src: "{{ repo_dest }}/target/hello-world-1.0.war"
        dest: "./artifacts/"
        flat: yes