---
- name: Build project
  hosts: build
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Copy Dockerfile
      copy:
        src: Dockerfile.build
        dest: /home/ubuntu/devops/